#ifndef __SENSORLESS_CONFIG_H__
#define __SENSORLESS_CONFIG_H__

#include "config.h"

/* 无感 FOC 的快慢环节拍：快环跟 ADC/PWM，慢环跑在 TIM7 的 1 kHz 子节拍上。 */
#define SENSORLESS_FAST_LOOP_FREQ              PWM_FREQ
#define SENSORLESS_FAST_LOOP_DT                (1.0f / (float)SENSORLESS_FAST_LOOP_FREQ)
#define SENSORLESS_SLOW_LOOP_FREQ              1000U
#define SENSORLESS_SLOW_LOOP_DIV               (SPEED_CALCU_FREQ / SENSORLESS_SLOW_LOOP_FREQ)
#define SENSORLESS_SLOW_LOOP_DT                (1.0f / (float)SENSORLESS_SLOW_LOOP_FREQ)

/* 启动链路参数：速度类宏统一按机械 rad/s 理解，模块内部再换算成电角速度。 */
#define SENSORLESS_CURRENT_CALIB_SAMPLES       1000U
#define SENSORLESS_ALIGN_VOLTAGE               1.2f
#define SENSORLESS_ALIGN_ANGLE_RAD             0.0f
#define SENSORLESS_ALIGN_DURATION_MS           400U
#define SENSORLESS_ALIGN_RESTART_DURATION_MS   180U
#define SENSORLESS_START_REQUEST_SPEED         3.0f
#define SENSORLESS_STOP_REQUEST_SPEED          0.5f
#define SENSORLESS_OPENLOOP_START_VOLTAGE      1.2f
#define SENSORLESS_OPENLOOP_END_VOLTAGE        4.5f
#define SENSORLESS_OPENLOOP_ACCEL_FAST         80.0f
#define SENSORLESS_OPENLOOP_ACCEL_MID          40.0f
#define SENSORLESS_OPENLOOP_ACCEL_SLOW         15.0f
#define SENSORLESS_TARGET_SLEW_RATE_FAST       80.0f
#define SENSORLESS_TARGET_SLEW_RATE_MID        40.0f
#define SENSORLESS_TARGET_SLEW_RATE_SLOW       15.0f
#define SENSORLESS_ACCEL_STAGE_SPEED1          20.0f
#define SENSORLESS_ACCEL_STAGE_SPEED2          55.0f
#define SENSORLESS_OPENLOOP_CURRENT_LIMIT      1.80f
#define SENSORLESS_OPENLOOP_CURRENT_RELEASE    1.20f
#define SENSORLESS_OPENLOOP_FOLDBACK_GAIN      0.020f
#define SENSORLESS_OPENLOOP_TRANSITION_SPEED   12.0f
#define SENSORLESS_OPENLOOP_MAX_SPEED          80.0f
#define SENSORLESS_OBSERVER_ENABLE_SPEED       6.0f

/* 开环到闭环的角度混合参数。 */
#define SENSORLESS_BLEND_RATE                  0.02f
#define SENSORLESS_TRANSITION_MAX_ANGLE_DEG    30.0f
#define SENSORLESS_TRANSITION_CONFIRM_TICKS    20U
#define SENSORLESS_TRANSITION_MIN_SPEED_RATIO  0.45f
#define SENSORLESS_TRANSITION_MAX_SPEED_RATIO  1.80f
#define SENSORLESS_TRANSITION_USABLE_MIN_SPEED_RATIO  0.20f
#define SENSORLESS_TRANSITION_USABLE_MAX_SPEED_RATIO  2.60f
    
/* SMO + PLL 参数，先给一套偏保守的默认值，后面可以按实机继续调。 */
#define SENSORLESS_RS                          5.1f
#define SENSORLESS_LS                          0.0028f
#define SENSORLESS_SMO_K_SLIDE                1.5f
#define SENSORLESS_SMO_LPF_ALPHA              0.24f
#define SENSORLESS_SMO_SAT_EPSILON            0.001f
#define SENSORLESS_SMO_CONVERGED_BEMF         0.30f
#define SENSORLESS_SMO_CONVERGED_CURRENT_ERR  0.10f
#define SENSORLESS_SMO_USABLE_BEMF            0.12f
#define SENSORLESS_SMO_USABLE_CURRENT_ERR     0.50f
#define SENSORLESS_PLL_KP                    300.0f
#define SENSORLESS_PLL_KI                   3000.0f
#define SENSORLESS_PLL_OMEGA_LIMIT           800.0f
#define SENSORLESS_PLL_SPEED_LPF_ALPHA         0.10f

/* 闭环控制参数：当前 W0 采用速度-电流串级控制。 */
#define SENSORLESS_SPEED_LOOP_KP               0.03f
#define SENSORLESS_SPEED_LOOP_KI               0.20f
#define SENSORLESS_SPEED_LOOP_KD               0.00f
#define SENSORLESS_SPEED_LOOP_CURRENT_LIMIT    0.80f
#define SENSORLESS_CURRENT_LOOP_KP             0.80f
#define SENSORLESS_CURRENT_LOOP_KI             0.005f
#define SENSORLESS_CURRENT_LOOP_UQ_LIMIT       (BUS_VOLTAGE * 0.5f)

/* 故障保护：过流由 adc.c 主保护兜底，这里补上失步/堵转等无感专有判据。 */
#define SENSORLESS_STALL_SPEED_THRESHOLD       2.0f
#define SENSORLESS_STALL_TIMEOUT_MS            500U
#define SENSORLESS_OBSERVER_LOST_TIMEOUT_MS    200U
#define SENSORLESS_UNDERVOLTAGE_THRESHOLD      0.0f

#endif
